version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  test-and-build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
        environment:
          MIX_ENV: prod
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
         key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # build and push Docker image
      - run: clean install
     

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy
